---
- name: OpenGrok | Add auto_index script (provided by playbooks)
  template:
    src: "{{ opengrok_auto_index_script_path}}"
    dest: "{{ opengrok_remote_auto_index }}"
    owner: "{{ opengrok_user }}"
    group: "{{ opengrok_group }}"
    mode: 0755

- name: OpenGrok | Ensure cron package is installed
  apt:
    pkg: cron

- name: OpenGrok | Add Cron Job to index periodically
  cron:
    name: OpenGrok | auto_index
    minute: "{{ opengrok_cron_job.minute }}"
    hour: "{{ opengrok_cron_job.hour }}"
    day: "{{ opengrok_cron_job.day }}"
    weekday: "{{ opengrok_cron_job.weekday }}"
    month: "{{ opengrok_cron_job.month }}"
    user: "{{ opengrok_cron_job.user }}"
    job: "{{ opengrok_remote_auto_index }}"
