---
- name: OpenGrok | Install
  import_tasks: install.yml
  tags:
    - opengrok_install

- name: OpenGrok | Deploy
  import_tasks: deploy.yml
  tags:
    - opengrok_deploy

- name: OpenGrok | Index
  import_tasks: index.yml
  tags:
    - opengrok_index

- name: OpenGrok | Configure auto index
  import_tasks: auto_index.yml
  tags:
    - opengrok_cron
    - opengrok_auto_index
  when: opengrok_auto_index
